name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop

strategy:
  matrix:
    go-version: ['1.23', '1.24']

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go
